# Generated by Django 4.1.3 on 2022-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_papland_survey_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papland',
            name='survey_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
