# Generated by Django 4.1.3 on 2023-01-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_croplist_created_croplist_owner_croplist_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crop_list', to='api.croplist'),
            preserve_default=False,
        ),
    ]
