# Generated by Django 4.1.3 on 2022-11-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_papland_survey_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='owner',
        ),
    ]
