# Generated by Django 4.1.3 on 2022-11-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_land_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={},
        ),
        migrations.RemoveField(
            model_name='land',
            name='description',
        ),
        migrations.RemoveField(
            model_name='land',
            name='name',
        ),
        migrations.AddField(
            model_name='land',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='land_image',
            field=models.ImageField(blank=True, upload_to='land_uploads'),
        ),
        migrations.AddField(
            model_name='land',
            name='land_services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='land',
            name='land_type',
            field=models.CharField(choices=[('Urban/Built-up Land', 'Urban/Built-up Land'), ('Agricultural Land', 'Agricultural Land'), ('Rangeland', 'Rangeland'), ('Forest Land', 'Forest Land'), ('Water Areas', 'Water Areas'), ('Wetland', 'Wetland'), ('Barren Land.', 'Barren Land'), ('Tundra', 'Tundra'), ('Perennial snow or ice', 'Perennial snow or ice'), ('Others(add in description)', 'Others(add in description)')], default='Agricultural Land', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='land_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='land',
            name='location',
            field=models.CharField(default='Kampala', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='pap',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='pap_lands', to='api.projectaffectedperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='rate',
            field=models.PositiveIntegerField(default=12000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='size',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='land',
            name='survey_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='land',
            name='tenure',
            field=models.CharField(choices=[('Mailo Land', 'Mailo Land'), ('Freehold Land', 'Freehold Land'), ('Lease Land', 'Lease Land'), ('Customary Land', 'Customary Land')], default='Mailo Land', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PAPLand',
        ),
    ]
