# Generated by Django 4.1.3 on 2023-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_crop_rating_treelist_tenuretype_landlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treelist',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
