# Generated by Django 4.1.3 on 2022-11-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_land_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_land_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
