# Generated by Django 4.1.3 on 2023-01-21 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_treelist_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_list_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenuretype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenure_list_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treelist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_list_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
