# Generated by Django 4.1.3 on 2023-01-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_landlist_owner_alter_tenuretype_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenuretype',
            name='owner',
        ),
    ]
