# Generated by Django 4.1.3 on 2022-11-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_land_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='owner',
            new_name='user',
        ),
    ]
