# Generated by Django 4.1.3 on 2022-11-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_constructionbuilding_number_of_construction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4')], default=5),
        ),
    ]
