# Generated by Django 4.1.3 on 2022-11-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_crop_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionbuilding',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='price',
            new_name='rate',
        ),
    ]
