# Generated by Django 4.1.3 on 2022-11-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_crop_pap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='pap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_crops', to='api.projectaffectedperson'),
        ),
    ]
