# Generated by Django 4.1.3 on 2022-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_crop_pap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='land',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='trees',
        ),
        migrations.AlterField(
            model_name='constructionbuilding',
            name='size',
            field=models.FloatField(blank=True, default=100.0),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.FloatField(blank=True, default=100.0),
        ),
    ]
