# Generated by Django 4.1.3 on 2022-11-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_projectaffectedperson_construction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbuilding',
            name='size',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
