# Generated by Django 4.1.3 on 2022-11-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_constructionbuilding_size_alter_land_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbuilding',
            name='size',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.FloatField(blank=True),
        ),
    ]
