# Generated by Django 4.1.3 on 2022-12-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_constructionbuilding_pap_alter_crop_pap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbuilding',
            name='pap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_construction', to='api.projectaffectedperson'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='pap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_crops', to='api.projectaffectedperson'),
        ),
        migrations.AlterField(
            model_name='land',
            name='pap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_lands', to='api.projectaffectedperson'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='pap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_trees', to='api.projectaffectedperson'),
        ),
    ]
